name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZDZhNGZkMzgtZmExYS00YjM3LWFkOWItNjc4MjE4OGYzZGViIiwidGVuYW50X2lkIjoiOWEwZjhiMGRjMmU2NWRhZDk0Y2Q4NDUzZDY4ZGIwZWY0ZDIyZGNjOTQ4MWUyNDkxYzNiZTUxMzU1NWQwMTAxNyIsImludGVybmFsX3NlY3JldCI6IjY1MjIwYTIxLWE0ZmItNGY4MC1iZWU1LTQzMjAyZGNmYWNmMiJ9.eq1kKsSMK2M85ugR4lSqyWaIa5fBjJZHDub4XnJS-1w"
key= "p8@#F2bI^4h3"
GEMINI_API_KEY="AIzaSyDd8sYJAB9MYbeFeDpmNgwkyp0qfN4sIMw"